// The new Next Day craft list, by MidnightRambler and some homies
// Если нужно добавить крафт добавляйте по разделам

// Базовые вещи и манипуляции
{1}{}{DEVIDER@Разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{5}{}{PID_GLASS_BOTTLE_FULL@Вы всегда знали, что это возможно!@@@PID_BOTTLE_FULL 1&PID_BOTTLE_GLASS 1@@PID_BOTTLE_EMPTY 1&PID_GLASS_BOTTLE_FULL 1@script fix_boy@fix_FreeHands}
{10}{}{PID_BOTTLE_FULL@Вы всегда знали, что это возможно!@@@PID_GLASS_BOTTLE_FULL 1&PID_BOTTLE_EMPTY 1@@PID_BOTTLE_FULL 1&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}
{15}{}{PID_MEAT_JERKY@Некоторые кусочки радиоактивного мясо ещё съедобны. Их лишь нужно замочить в маринаде, а затем прокоптить. Не очень сытно, но вполне съедобно.@@SK_SCIENCE 60|SK_OUTDOORSMAN 85@PID_RAD_MEAT 3&PID_BOOZE 1@PID_FIREPLACE_TOKEN 1@PID_MEAT_JERKY 2@script fix_boy@fix_FreeHands}
{20}{}{PID_SHARPENED_POLE@Вытачиваем длинную палку для ваших нужд.@@SK_OUTDOORSMAN 30@PID_FIREWOOD 1@PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_SHARPENED_POLE 1@script fix_boy@fix_FreeHands}
{25}{}{PID_SANDBAG_1@Вы всегда знали, что это возможно!@@@PID_SANDBAG_EMPTY 1@PID_SHOVEL 1@PID_SANDBAG_1 1@script fix_boy@fix_FreeHands}
{30}{}{PID_SANDBAG_EMPTY@Мешок. Да, его можно сшить.@@SK_REPAIR 40|SK_OUTDOORSMAN 40@PID_CRAFT_L_RAGS 6&PID_MEDTHREAD 4@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_SANDBAG_EMPTY 1@script fix_boy@fix_FreeHands}
{35}{}{PID_SHARPENED_POLE@Вытачиваем длинную палку для ваших нужд.@@SK_OUTDOORSMAN 30@PID_FIREWOOD 1@PID_KNIFE 1|PID_THROWING_KNIFE 1|PID_COMBAT_KNIFE 1@PID_SHARPENED_POLE 1@script fix_boy@fix_FreeHands}
{40}{}{PID_MEDTHREAD@Вручную выпрядь полметра низкокачественных ниток - задача не сложная, но крайне занудная.@@@PID_CRAFT_L_LINT 2@PID_SHIV 1@PID_MEDTHREAD 1@script fix_boy@fix_FreeHands}
{45}{}{PID_ROPE@Из пары тряпок можно сделать что-то похожее на кусочек веревки.@@@PID_CRAFT_L_LINT 2@@PID_PART_OF_ROPE 1@script fix_boy@fix_FreeHands}
{50}{}{PID_ROPE@Свяжите из множества кусков веревки одну целую. Получится узловатая, грубая, но все же веревка.@@@PID_PART_OF_ROPE 6@@PID_ROPE 1@script fix_boy@fix_FreeHands}
{55}{}{PID_WOOD_PLANK@Немного сточить там-сям, и готово. Выглядит, конечно, так себе.@@SK_REPAIR 50@PID_FIREWOOD 3@PID_REVFIST1 1|PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_WOOD_PLANK 2@script fix_boy@fix_FreeHands}
{60}{}{PID_WOOD_PART@Убираем все неровности у неказистой деревяшки с помощью рубанка и пары инструментов. Гораздо лучше, а?@@SK_REPAIR 50|SK_OUTDOORSMAN 50@PID_WOOD_PLANK 1|PID_FIREWOOD 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_WOOD_PART 1@script fix_boy@fix_FreeHands}
{65}{}{PID_CRAFT_L_LINT@Разрезаем ножом тряпку на кусочки.@@@PID_CRAFT_L_RAGS 1@PID_KNIFE 1|PID_COMBAT_KNIFE 1|PID_SCISSORS 1@PID_CRAFT_L_LINT 2@script fix_boy@fix_FreeHands}
{70}{}{PID_CRAFT_L_HIDE@Ваших познаний достаточно, что бы выдубить имеющиеся шкуры и получить из неё шматы кожи.@@SK_SCIENCE 100|SK_OUTDOORSMAN 125@PID_BRAHMIN_SKIN 1|PID_GOLDEN_GECKO_PELT 2|PID_GECKO_PELT 3|PID_MOUSE_SKIN 16&PID_CHEMICALS 1@PID_FIREPLACE_TOKEN 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_CRAFT_L_HIDE 6&PID_BOTTLE_GLASS 1@script fix_boy@fix_FreeHands}
{75}{}{PID_SHORT_TUBE@Распиливаем длинную трубу на две маленькие.@@SK_REPAIR 50@PID_TUBE 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SHORT_TUBE 2@script fix_boy@fix_FreeHands}
{80}{}{PID_REVOLVER_PART@Используя банку в качестве корпуса, вы собираете в ней камеры для пуль.@@SK_REPAIR 40&SK_SCIENCE 25@PID_BANKA_MEH 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1@PID_REVOLVER_PART 1@script fix_boy@fix_FreeHands}

// Продвинутый стафф и то, что не вошло в 1
{150}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{155}{}{PID_BAG@Чтобы сделать вместительную сумку достаточно просто связать конец веревкой.@@@PID_SANDBAG_EMPTY 1&PID_ROPE 1@@PID_BAG 1@script fix_boy@fix_FreeHands}
{160}{}{PID_BACKPACK@Делаем из ветхой сумки что-то достойное с помощью пары незамысловатых инструментов.@@SK_REPAIR 75&SK_SCIENCE 75|SK_OUTDOORSMAN 125@PID_BAG 1&PID_CRAFT_L_HIDE 4&PID_MEDTHREAD 4&PID_PART_OF_ROPE 2@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_BACKPACK 1@script fix_boy@fix_FreeHands}
{165}{}{PID_ROD@Соединяем две длинные палки, присобачиваем несколько колец для лески. Примитивная удочка готова!@@SK_OUTDOORSMAN 100|SK_REPAIR 75@PID_SHARPENED_POLE 2&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_ROD 1@exp 100 script fix_boy@fix_FreeHands}
{170}{}{PID_HOOK@Придётся попотеть, но с помощью кусачек, горелки, шила и молотка можно сделать вполне пригодные рыболовные снасти.@@SK_OUTDOORSMAN 100|SK_REPAIR 75@PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_SHIV 1&PID_SLEDGEHAMMER 1@PID_HOOK 1@exp 100 script fix_boy@fix_FreeHands}
{175}{}{PID_STRING@Вытягиваем длинную леску из старых пластиковых бутылок. Работа довольно кропотливая.@@SK_OUTDOORSMAN 100|SK_REPAIR 75@PID_BOTTLE_EMPTY 3&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1&PID_SUPER_TOOL_KIT 1&PID_LIGHTER 1&PID_SHIV 1&PID_SLEDGEHAMMER 1@PID_STRING 1@exp 100 script fix_boy@fix_FreeHands}
{180}{}{PID_RADIO@Вам одиноко? Не с кем общаться? Вокруг одни сволочи и кротокрысы? Вам хочется об этом поговорить? Специально для вас! Нужную информацию можно найти в каждом номере "Электроники Дина"!@@SK_SCIENCE 125&SK_REPAIR 100@PID_CRAFT_E_CHIP 2&PID_CRAFT_M_JUNK 2&PID_CRAFT_E_LAMP 3&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@script fix_boy@fix_HighTech}
{185}{}{PID_RADIO@Откопали где-то неработающую рацию? Если есть смекалка и книга по электронике можно привести этого малыша в чувство!@@SK_SCIENCE 125&SK_REPAIR 100@PID_CRAFT_E_CHIP 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_E_LAMP 1&PID_VIC_RADIO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_DEANS_ELECTRONICS 1@PID_RADIO 1@script fix_boy@fix_HighTech}
{190}{}{PID_KOSYAK@Вы так сильно хотите "дунуть", что готовы перебрать и сточить ворох малопригодного сырья, лишь бы сделать хотя бы один нормальный косячок.@PE_FLOWER_CHILD 1@SK_OUTDOORSMAN 100&PE_FLOWER_CHILD 1@PID_BROC_FLOWER 5&PID_XANDER_ROOT 5&PID_CRAFT_L_RAGS 1&PID_FLOWER 1@@PID_KOSYAK 1@script fix_boy@fix_FreeHands}
{195}{}{PID_KOSYAK@Вы знаете, как обращаться с настоящей дурью, а не аналогами из сорняков. Но что бы курево не ушло за одну ходку, вы разводите им обычные сигареты.@PE_FLOWER_CHILD 1@SK_OUTDOORSMAN 30&PE_FLOWER_CHILD 1@PID_CIGARETTES 1&PID_MUTARIJUANA 2@@PID_KOSYAK 5@script fix_boy@fix_FreeHands}
{200}{}{PID_DEFIB@Стандартный реанимационный набор для восстановления жизнедеятельности. Можно собрать, имея нужные познания в медицине.@@SK_SCIENCE 100&SK_REPAIR 125&SK_DOCTOR 75|SK_FIRST_AID 75@PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 2&PID_STIMPAK 2&PID_CRAFT_E_CHIP 1&PID_BAG 1&PID_WORKBENCH_TOKEN 1&PID_SMALL_ENERGY_CELL 5|PID_MICRO_FUSION_CELL 1@PID_SUPER_TOOL_KIT 1@PID_DEFIB 1@script fix_boy@fix_HighTech}
{205}{}{PID_HANDCUFFS@Довольно крепкие наручники из подручных средств.@@SK_SCIENCE 100&SK_REPAIR 150@PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_IRON_DETALS 1&PID_CHAIN 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_HANDCUFFS 1@script fix_boy@fix_Repair}
{210}{}{PID_LOCKER_LOW@Самый просто навесной замок. Проще некуда.@@SK_REPAIR 50&SK_LOCKPICK 40@PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 2&PID_HLAM_MEH 1|PID_HLAM2_MEH 1|PID_METAL_LIST_MEH 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_LOCKER_LOW 1@exp 100 script fix_boy@fix_FreeHands}
{215}{}{PID_LOCKER_MED@Замок среднего уровня. Может от кого-то и спасет.@@SK_REPAIR 75|SK_LOCKPICK 60@PID_CRAFT_M_BARS 8&PID_CRAFT_M_JUNK 2&PID_HLAM_MEH 1|PID_HLAM2_MEH 1|PID_METAL_LIST_MEH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_LOCKER_MED 1@exp 200 script fix_boy@fix_Advanced}
{220}{}{PID_LOCKER_HARD@Хех, куда же такой сейф ставить?@@SK_REPAIR 125&SK_LOCKPICK 75@PID_CRAFT_M_BARS 12&PID_CRAFT_M_JUNK 1&PID_HLAM_MEH 2|PID_HLAM2_MEH 2|PID_METAL_LIST_MEH 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_LOCKER_HARD 1@exp 300 script fix_boy@fix_Advanced}
{225}{}{PID_LOCKPICKS@Вы разбираетесь в этом деле и можете сами себе изготовить отмычки. В красивом кожаном чехле. Они дорогого стоят.@@SK_LOCKPICK 75@PID_CRAFT_M_STEL 1&PID_IRON_DETALS 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 2&PID_CRAFT_L_HIDE 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_LOCKPICKS 1@script fix_boy@fix_Repair}
{230}{}{PID_EXP_LOCKPICK_SET@Профессионалы вроде вас работают только с качественными инструментами и экипировкой! Такой набор - на вес золота.@@SK_LOCKPICK 150@PID_LOCKPICKS 2&PID_MULTI_TOOL 1&PID_CRAFT_L_HIDE 1&PID_WORKBENCH_TOKEN 1@PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_EXP_LOCKPICK_SET 1@script fix_boy@fix_HighTech}

// инструменты всякоразные
{300}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{305}{}{PID_SCISSORS@Точим лезвия, собираем простенькую рукоять из лишнего железа, закрепляем все болтом.@@SK_REPAIR 30|SK_OUTDOORSMAN 75@PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 1&PID_FLINT 1@@PID_SCISSORS 1@script fix_boy@fix_FreeHands}
{310}{}{PID_SHIV@Вырежьте из дерева рукоять, а потом забейте в неё железяку. Получилось шило, универсальный инструмент для проделывания дырок.@@SK_OUTDOORSMAN 30|SK_REPAIR 25@PID_CRAFT_M_BARS 1&PID_WOOD_PLANK 1@PID_KNIFE 1@PID_SHIV 1@script fix_boy@fix_FreeHands}
{315}{}{PID_MEDNEEDLE@Ваших знаний вполне хватает на то, что бы выточить простую медицинскую иглу из заранее подготовленного острого куска металла.@@SK_FIRST_AID 70|SK_SCIENCE 50|SK_DOCTOR 50|SK_REPAIR 50@PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1@PID_MEDNEEDLE 1@script fix_boy@fix_FreeHands}
{320}{}{PID_KNIFE@Удобно лежит в руке и хорошо выглядит - что ещё нужно от ножа? Ещё бы только не пришлось его так долго вытачивать..@@SK_REPAIR 30|SK_OUTDOORSMAN 50@PID_WOOD_PLANK 1&PID_METAL_LIST_MEH 1&PID_CRAFT_M_BARS 1@PID_FLINT 1@PID_KNIFE 1@script fix_boy@fix_FreeHands}
{325}{}{PID_CUTTHROAT@Вытачиваем из деревяшки подходящую рукоять, натачиваем железо до бритвенной остроты.@@SK_REPAIR 30|SK_OUTDOORSMAN 40@PID_CLUB 1&PID_CRAFT_M_BARS 2&PID_FLINT 1@PID_KNIFE 1@PID_CUTTHROAT 1@script fix_boy@fix_FreeHands}
{330}{}{PID_MULTI_TOOL@Прийдётся попотеть, но с помощью отвёртки и молотка можно собрать простенькие инструменты на коленке.@@SK_OUTDOORSMAN 100|SK_REPAIR 70@PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 2@PID_SHIV 1&PID_SLEDGEHAMMER 1@PID_MULTI_TOOL 1@script fix_boy@fix_FreeHands}
{335}{}{PID_AXE@Насадите железяку поострее на палку покрепче.@@SK_OUTDOORSMAN 30@PID_CRAFT_M_BARS 2|PID_HLAM_MEH 1|PID_HLAM2_MEH 1|PID_METAL_LIST_MEH 1&PID_WOOD_PLANK 1@PID_ROCK 1@PID_AXE 1@script fix_boy@fix_FreeHands}
{340}{}{PID_SLEDGEHAMMER@Насадите железный брус потяжелее на палку покрепче, камни идут как ударники.@@SK_OUTDOORSMAN 40|SK_REPAIR 35@PID_IRON_BAR 1&PID_ROCK 2&PID_PART_OF_ROPE 2&PID_WOOD_PLANK 1@@PID_SLEDGEHAMMER 1@script fix_boy@fix_FreeHands}
{345}{}{PID_CROWBAR@Нежными ударами придайте трубе правильную форму.@@SK_REPAIR 30@PID_TUBE 1@PID_SLEDGEHAMMER 1@PID_CROWBAR 1@script fix_boy@fix_FreeHands}
{350}{}{PID_WELDING@Берем батареи на блок питания для дуги, кусачки пойдут как удержатель электрода, а куча хлама на сами электроды.@@SK_REPAIR 100&SK_SCIENCE 100@PID_CUENCELL_LOW 8|PID_SMALL_ENERGY_CELL 4&PID_MULTI_TOOL 1&PID_CRAFT_M_BARS 4&PID_EMKOCT_MEH 1&PID_WORKBENCH_TOKEN 1@@PID_WELDING 1@script fix_boy@fix_Advanced}
{355}{}{PID_WELDING@Берем несколько ёмкостей, наполняем их топливом и активирем реагентом.@@SK_REPAIR 75&SK_SCIENCE 100@PID_FLAMETHROWER_FUEL 8&PID_MULTI_TOOL 1&PID_CRAFT_M_BARS 4&PID_EMKOCT_MEH 3&PID_WORKBENCH_TOKEN 1@@PID_WELDING 1@script fix_boy@fix_Advanced}
{360}{}{PID_WELDING@Перезаряжаем использованную сварку.@@SK_REPAIR 70&SK_SCIENCE 50@PID_FLAMETHROWER_FUEL 8&PID_WELDING_USED 1@@PID_WELDING 1@script fix_boy@fix_FreeHands}
{365}{}{PID_SHOVEL@Найдите где-нибудь палку и насадите на один из ее концов подходящую железку.@@SK_REPAIR 50|SK_OUTDOORSMAN 75@PID_METAL_LIST_MEH 1&PID_SHARPENED_POLE 1&PID_PART_OF_ROPE 2@@PID_SHOVEL 1@script fix_boy@fix_FreeHands}
{370}{}{PID_LIGHTER@Соберите простенький корпус для самодельной Зиппо, набейте его смоченной в керосине ватой и закройте, добавив фитиль из тряпки в том-же керосине, и кремень для высекания искр. Огоньку?@@SK_SCIENCE 75|SK_REPAIR 75@PID_BANKA_MEH 1&PID_FLINT 1&PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1&PID_BOOZE 1&PID_CHEMICALS 1@@PID_LIGHTER 1@script fix_boy@fix_Advanced}
{375}{}{PID_LIGHTER@Соберите простенький корпус для самодельной Зиппо, теперь в новом футляре.@@SK_SCIENCE 70|SK_REPAIR 80@PID_PB_FOR_AMMO 1&PID_FLINT 1&PID_CRAFT_M_BARS 1&PID_CRAFT_L_RAGS 1&PID_FLAMETHROWER_FUEL 2@PID_MULTI_TOOL 1@PID_LIGHTER 1@script fix_boy@fix_Advanced}
{380}{}{PID_WRENCH@Разводной ключ. Собрать такой довольно тяжело, да.@@SK_REPAIR 100@PID_IRON_DETALS 1&PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 1@PID_WELDING 1&PID_MULTI_TOOL 1@PID_WRENCH 1@script fix_boy@fix_Advanced}

// оружия для братух-борцух (рукопашка)
{500}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{505}{}{PID_REVFIST1@Примитивный инструмент из подручных средств. Жаль, что одноразовый - очень быстро стачивается.@@@PID_ROCK 6|PID_FLINT 1|PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1@@PID_REVFIST1 1@script fix_boy@fix_FreeHands}
{510{}{PID_BRASS_KNUCKLES@Пробейте дырки для пальцев в подходящей железяке, сможете попугать кого-нибудь. Только в драку с такой ерундой лучше не лезть.@SK_UNARMED 30@SK_UNARMED 50&SK_REPAIR 50@PID_METAL_LIST_MEH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_BRASS_KNUCKLES 1@script fix_boy@fix_FreeHands}
{515}{}{PID_SPIKED_KNUCKLES@Гуманизм - это для слабых. Не пожалейте денег на сварку, чтобы приварить шипы к своему старому кастету, четыре дырки в противнике того стоят.@SK_REPAIR 40@SK_REPAIR 55@PID_BRASS_KNUCKLES 1&PID_SPIKE_MEH 4@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SPIKED_KNUCKLES 1@script fix_boy@fix_FreeHands}
{520}{}{PID_CHAIN@Хорошая вещица! И врага полоснуть, и на шею повесить, и на джинсах закрепить для крутости можно.@@SK_REPAIR 50|SK_MELEE_WEAPONS 60@PID_CRAFT_M_BARS 4@PID_MULTI_TOOL 1@PID_CHAIN 1@script fix_boy@fix_FreeHands}

// холодное оружие
{700}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{705}{}{PID_REVKNIFE1@Примитивное подобие ножа из подручного металлолома.@@SK_OUTDOORSMAN 50@PID_CRAFT_M_BARS 1|PID_HLAM_MEH 1|PID_HLAM2_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE1 1@script fix_boy@fix_FreeHands}
{710}{}{PID_REVKNIFE2@Взяв за основу более крупный кусок металла, можно выточить грубое мачете.@@SK_REPAIR 50@PID_METAL_LIST_MEH 1&PID_REVFIST1 1@@PID_REVKNIFE2 1@script fix_boy@fix_FreeHands}
{715}{}{PID_REVCLUB1@Шипы и лезвия - вот то, чего не хватало вашей дубине!@@SK_REPAIR 50@PID_CLUB 1&PID_REVFIST1 2&PID_CRAFT_M_BARS 1@@PID_REVCLUB1 1@script fix_boy@fix_FreeHands}
{720}{}{PID_CLUB@Как оказалось, сделать устрашающего вида дубину может почти каждый!@@SK_REPAIR 50@PID_WOOD_PLANK 1|PID_WOOD_PART 1@@PID_CLUB 1@script fix_boy@fix_FreeHands}Ъ
{725}{}{PID_LOUISVILLE_SLUGGER@С любовью вытачиваем биту из деревянной доски, затем покрываем лаком или химикатом для устойчивости от внешних воздействий.@@SK_REPAIR 50&SK_SCIENCE 50@PID_WOOD_PLANK 1|PID_WOOD_PART 1&PID_CHEMICALS 1@@PID_LOUISVILLE_SLUGGER 1@exp 25 script fix_boy@fix_FreeHands}
{730}{}{PID_COMBAT_KNIFE@Закалить лезвие, обмотать рукоять кожей, и этот нож уже можно называть оружием.@@SK_SCIENCE 60&SK_REPAIR 75&SK_MELEE_WEAPONS 80@PID_IRON_PLATE 1&PID_WOOD_PLANK 1&PID_CRAFT_L_HIDE 1&PID_FLINT 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_COMBAT_KNIFE 1@script fix_boy@fix_Advanced}
{735}{}{PID_SPEAR@Привяжите нож к палке. Это даст вам целый метр преимущества и килограмм уверенности.@@SK_OUTDOORSMAN 30&SK_MELEE_WEAPONS 40@PID_KNIFE 1&PID_ROPE 1&PID_SHARPENED_POLE 1@@PID_SPEAR 1@script fix_boy@fix_FreeHands}
{740}{}{PID_SHARP_SPEAR@Затачиваем ваше копье, затем делает пару зарубок, чтобы жертве было больнее.@SK_OUTDOORSMAN 40@SK_MELEE_WEAPONS 40&SK_REPAIR 20&SK_OUTDOORSMAN 40@PID_SPEAR 1&PID_FLINT 1@@PID_SHARP_SPEAR 1@script fix_boy@fix_FreeHands}
{745}{}{PID_KNIFE_P@Обмакните нож ядом как следует, и ваш противник будет повержен в кратчайшие сроки.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_KNIFE 1&PID_SCORPION_TAIL 4@PID_BANKA_MEH 1@PID_KNIFE_P 1@script fix_boy@fix_FreeHands}
{750}{}{PID_SPEAK_P@Острое как бритва, и ядовитое как опасный враг путешественника@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SPEAR 1&PID_SCORPION_TAIL 4@PID_BANKA_MEH 1@PID_SPEAK_P 1@script fix_boy@fix_FreeHands}
{755}{}{PID_СKNIFE_P@Верный боевой нож. Теперь и с ядом! Ограниченная партия!@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 4&PID_COMBAT_KNIFE 1@PID_BANKA_MEH 1@PID_CKNIFE_P 1@script fix_boy@fix_FreeHands}

// throwing shit
{900}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{905}{}{PID_THROWING_KNIFE@Вырезаем и затачиваем метательные ножи.@@SK_THROWING 100&SK_REPAIR 50@PID_IRON_PLATE 1&PID_FLINT 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_THROWING_KNIFE 3@script fix_boy@fix_Advanced}
{910}{}{PID_REV_BALL1@Плавим пластик, добавляем пару острых шипов и веревку - готово, ни одна жертва не ускользнет!@@SK_THROWING 50@PID_PART_OF_ROPE 3&PID_BOTTLE_EMPTY 3&PID_SPIKE_MEH 2@@PID_REV_BALL1 1@script fix_boy@fix_FreeHands}
{915}{}{PID_REV_BALL2@Модернизируем путы как можем.@@SK_THROWING 100|SK_SCIENCE 50@PID_REV_BALL1 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1|PID_CHEMICALS 1@@PID_REV_BALL2 1@script fix_boy@fix_FreeHands}
{920}{}{PID_MKNIFE_P@Метательный и ядовитый. Гремучая смесь.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 60@PID_SCORPION_TAIL 3&PID_THROWING_KNIFE 1@@PID_MKNIFE_P 1@script fix_boy@fix_FreeHands}
{925}{}{PID_MOLOTOV_COCKTAIL@Пойло, смешанное со смолянистым соком цветков, будет замечательно гореть и прилипать к противнику.@SK_SCIENCE 20@SK_SCIENCE 30&SK_OUTDOORSMAN 30@PID_ROT_GUT 1&PID_CRAFT_L_RAGS 1&PID_BROC_FLOWER 5@@PID_MOLOTOV_COCKTAIL 1@script fix_boy@fix_FreeHands}

// чисто медикаменты бомжиные и не очень
{1100}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{1105}{}{PID_HEALING_POWDER@Разотрите камнем высушенные на солнце ингредиенты и заверните в тряпочку.@SK_OUTDOORSMAN 20@SK_OUTDOORSMAN 40|SK_FIRST_AID 50@PID_BROC_FLOWER 1&PID_XANDER_ROOT 1&PID_CRAFT_L_RAGS 1@PID_REVFIST1 1|PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_HEALING_POWDER 1@script fix_boy@fix_FreeHands}
{1110}{}{PID_STIMPAK@Растворите целебный порошок в воде, наполните этой смесью стеклянный шприц и прокипятите. Потом простерилизуйте иглу спиртом.@@SK_FIRST_AID 120|SK_SCIENCE 100|SK_DOCTOR 75@PID_BOTTLE_FULL 2&PID_BOOZE 1&PID_HYPODERMIC_NEEDLE 1&PID_HEALING_POWDER 2@PID_LAB_TOKEN 1&PID_FIRST_AID_BOOK 1&PID_CHEMISTRY_MANUAL 1@PID_STIMPAK 1&PID_BOTTLE_EMPTY 3@script fix_boy@fix_Science}
{1115}{}{PID_ANTIDOTE@Это будет скорей самовнушением. @SK_OUTDOORSMAN 30@SK_OUTDOORSMAN 40&SK_DOCTOR 30@PID_BOOZE 1&PID_SCORPION_TAIL 1|PID_XANDER_ROOT 3@PID_LIGHTER 1@PID_ANTIDOTE 1@script fix_boy@fix_FreeHands}
{1125}{}{PID_ANESTETIC@Руководствуясь по химическим журналам, вы успешно синтезируете кустарный анестетик из подручных материалов.@@SK_SCIENCE 100|SK_FIRST_AID 120&SK_DOCTOR 100|SK_OUTDOORSMAN 120@PID_BOOZE 1&PID_ANTIDOTE 1&PID_BOTTLE_FULL 2&PID_FLOWER 2&PID_HYPODERMIC_NEEDLE 2@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_ANESTETIC 2@script fix_boy@fix_Science3}
{1130}{}{PID_ANTISEPTIC@Руководствуясь по химическим журналам, вы успешно синтезируете кустарный антисептик из подручных материалов.@@SK_SCIENCE 100|SK_FIRST_AID 120&SK_DOCTOR 100|SK_OUTDOORSMAN 120@PID_BOOZE 2&PID_ANTIDOTE 1&PID_BOTTLE_FULL 3&PID_FLOWER 2&PID_CHEMICALS 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_ANTISEPTIC 3@script fix_boy@fix_Science3}
{1135}{}{PID_BANDAGE@Ваших знаний вполне хватает на то, что бы простерилизовать и подготовить бинт из подручных материалов.@@SK_FIRST_AID 80|SK_SCIENCE 60|SK_DOCTOR 50|SK_OUTDOORSMAN 75@PID_BOOZE 1&PID_CRAFT_L_RAGS 3@@PID_BANDAGE 2@script fix_boy@fix_FreeHands}
{1140}{}{PID_ANTIDOTE_2@Мощное противоядие, нейтрализующее действие нейротоксина. Можно сделать, имея образец токсина.@SK_SCIENCE 60@SK_SCIENCE 100@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 3&PID_BOTTLE_GLASS 2&PID_HYPO_POISON 1@PID_CHEMISTRY_MANUAL 1&PID_LAB_TOKEN 1@PID_ANTIDOTE_2 3@script fix_boy@fix_Science3}
{1145}{}{PID_HEART_PILLS@Никогда не знаешь, когда пригодятся лекарства от сердечной недостаточности.@@SK_SCIENCE 100|SK_FIRST_AID 120&SK_DOCTOR 100@PID_HEALING_POWDER 3&PID_BROC_FLOWER 5&PID_XANDER_ROOT 4&PID_BOTTLE_FULL 2&PID_CRAFT_L_RAGS 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_HEART_PILLS 1&PID_BOTTLE_GLASS 2@script fix_boy@fix_Science}
{1150}{}{PID_PILLS@Брок выварить в кипятке и выстоять в течении часа, процедить. Пока выстаивается отвар, приготовьте основу для таблеткок на основе клейстера. Катализатором фармокологического действия, а также замечательным консервантом станет эмульсия из обычного порошка. Соблюдайте стерильность!@@SK_SCIENCE 75&SK_DOCTOR 100@PID_BOOZE 1&PID_XANDER_ROOT 3&PID_FLOWER 1&PID_ANTISEPTIC 1&PID_HEALING_POWDER 1&PID_CHEMICALS 1&PID_GLASS_BOTTLE_FULL 1@PID_LAB_TOKEN 1@PID_PILLS 1&PID_BOTTLE_GLASS 3@script fix_boy@fix_Science}
{1155}{}{PID_MEDCLIP@Любому доктору нужен этот инструмент.@@SK_FIRST_AID 80|SK_SCIENCE 60|SK_DOCTOR 50|SK_REPAIR 75@PID_CRAFT_M_BARS 2@PID_WORKBENCH_TOKEN 1&PID_LIGHTER 1@PID_MEDCLIP 1@script fix_boy@fix_FreeHands}
{1160}{}{PID_MEDSPLINT@Ваших знаний вполне хватает на то, что бы соорудить простую медицинскую шину из подручных материалов.@@SK_FIRST_AID 80|SK_SCIENCE 60|SK_DOCTOR 50|SK_REPAIR 75@PID_PART_OF_ROPE 2&PID_WOOD_PLANK 1@@PID_MEDSPLINT 1@script fix_boy@fix_FreeHands}

// химикаты, и все что связано
{1300}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{1302}{}{PID_GLASS_BOTTLE_FULL@Постепенно кипятим несколько литров грязной воды в небольшой посудине. Не забудьте отфильтровать крупный мусор через тряпку, и можно пить!@@SK_SCIENCE 50&SK_OUTDOORSMAN 75@PID_GLASS_BOTTLE_DIRTY_FULL 3@PID_FIREPLACE_TOKEN 1&PID_BANKA_MEH 1&PID_CRAFT_L_RAGS 1@PID_GLASS_BOTTLE_FULL 1&PID_BOTTLE_GLASS 2@exp 10 script fix_boy@fix_FreeHands}
{1303}{}{PID_BOTTLE_FULL@Постепенно кипятим несколько литров грязной воды в небольшой посудине. Не забудьте отфильтровать крупный мусор через тряпку, и можно пить!@@SK_SCIENCE 50&SK_OUTDOORSMAN 75@PID_BOTTLE_DIRTY_FULL 3@PID_FIREPLACE_TOKEN 1&PID_BANKA_MEH 1&PID_CRAFT_L_RAGS 1@PID_BOTTLE_FULL 1&PID_BOTTLE_EMPTY 2@exp 10 script fix_boy@fix_FreeHands}
{1305}{}{PID_MINERAL@Благодаря вашим обширным познаниям и подсказкам из химических журналов, вы можете найти хоть что-то ценное в этой груде бесполезной породы.@@SK_SCIENCE 150&SK_REPAIR 100@PID_BOTTLE_FULL 3&PID_METAL_ORE 1|PID_ROCK 20@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1&PID_SLEDGEHAMMER 1@PID_MINERAL 1@exp 25 script fix_boy@fix_Science3}
{1310}{}{PID_CHEMICALS@Благодаря вашим обширным познаниям и подсказкам из химических журналов, вы можете выделить основные химические реагенты из подручных материалов.@@SK_SCIENCE 150@PID_BOOZE 1&PID_BOTTLE_FULL 1&PID_MINERAL 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_CHEMICALS 2@exp 25 script fix_boy@fix_Science3}
{1315}{}{PID_TNT@Смешайте азотную кислоту с серной и постепенно вливайте в толуол, постоянно нагревая, осадок просушите и поместите в какую-нибудь банку.@SK_SCIENCE 80@SK_SCIENCE 100@PID_CHEMICALS 3&PID_BOTTLE_FULL 2&PID_CRAFT_M_JUNK 1|PID_BANKA_MEH 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_TNT 1@exp 150 script fix_boy@fix_Science3}
{1320}{}{PID_NITROGLYCERIN@Отделите жир от мяса, смешивайте с азотной и серной кислотой для получения нитроглицерина. Следите за тем, чтобы смесь не перегревалась во время реакции.@SK_SCIENCE 90@SK_SCIENCE 110&SK_OUTDOORSMAN 50@PID_MEAT 1&PID_CHEMICALS 2&PID_BOTTLE_FULL 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_NITROGLYCERIN 1&PID_BOTTLE_GLASS 2@script fix_boy@fix_Science3}
{1325}{}{PID_HEXOGEN@Руководствуясь по химическим журналам, вы успешно получаете гексоген из подручных материалов.@SK_TRAPS 50&SK_SCIENCE 80@SK_TRAPS 100&SK_SCIENCE 150@PID_CHEMICALS 2&PID_BOTTLE_FULL 2&PID_MINERAL 1@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1@PID_HEXOGEN 1@exp 100 script fix_boy@fix_Science3}
{1430}{}{PID_HYPO_POISON@Сильнейший нейротоксин, который в малых количествах содержится в ядовитом жале радскорпионов можно извлечь методом кислотно-щелочной экстракции.@SK_SCIENCE 80@SK_SCIENCE 140@PID_CHEMICALS 1&PID_HYPODERMIC_NEEDLE 1&PID_BOTTLE_GLASS 2&PID_SCORPION_TAIL 8@PID_SUPER_TOOL_KIT 1&PID_LAB_TOKEN 1&PID_KNIFE 1@PID_HYPO_POISON 1@script fix_boy@fix_Science3}
{1435}{}{PID_GUNPOWDER@Используйте кислоту для получения калийной селитры, смешайте 6 частей селитры с 1 частью угля и 1 серы.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 50&SK_SCIENCE 80@PID_MINERAL 1&PID_CHEMICALS 1&PID_MUSH_LOW 3@PID_LAB_TOKEN 1&PID_CHEMISTRY_MANUAL 1&PID_ROCK 1|PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_GUNPOWDER 3&PID_BOTTLE_GLASS 1@script fix_boy@fix_Science3}

// все что касается самопальных патрон
{1500}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{1505}{}{PID_PB_FOR_AMMO@Нехитрым приспособлением можно быстро клепать болванки гильз и заготовки для пуль.@@SK_REPAIR 70&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1|PID_METAL_LIST_MEH 1&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1&PID_MULTI_TOOL 1@PID_PB_FOR_AMMO 3@script fix_boy@fix_Science}
{1510}{}{PID_10mm_LOW@Засыпать порох в старые гильзы, вставить самодельную пулю.@@SK_REPAIR 80&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_CRAFT_M_BARS 2&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_10mm_LOW 5@script fix_boy@fix_Science}
{1515}{}{PID_044mag_LOW@Засыпать порох в старые гильзы, вставить самодельную пулю.@@SK_REPAIR 80&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_CRAFT_M_BARS 2&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_044mag_LOW 4@script fix_boy@fix_Science}
{1520}{}{PID_14mm_LOW@Засыпать порох в гильзу, вставить пулю@@SK_REPAIR 80&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_GUNPOWDER 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_14mm_LOW 5@script fix_boy@fix_Science}
{1525}{}{PID_12g_LOW@Выпарить грибы, засыпать получившийся порошок в заготовку, насыпать обломков гвоздей.@@SK_REPAIR 80&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_PB_FOR_AMMO 1&PID_MUSH_LOW 2&PID_CRAFT_L_RAGS 1&PID_CRAFT_M_JUNK 2|PID_CRAFT_M_BARS 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1@PID_12g_LOW 6@script fix_boy@fix_Science}
{1530}{}{PID_223_LOW@Засыпать порох в старые гильзы, вставить самодельную пулю.@@SK_REPAIR 80&SK_SMALL_GUNS 60|SK_BIG_GUNS 60@PID_CRAFT_M_BARS 2&PID_GUNPOWDER 1&PID_PB_FOR_AMMO 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_223_LOW 4@script fix_boy@fix_Science}
{1535}{}{PID_CUENCELL_LOW@Извлекаем из радэлементов компоненты, готовим электролит, добавляем реагенты, обматываем фольгой и закрываем в корпус.@@SK_SCIENCE 120&SK_REPAIR 100@PID_RAD_LOW 1&PID_CHEMICALS 1&PID_CRAFT_M_BARS 3&PID_BANKA_MEH 1@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_CUENCELL_LOW 5@script fix_boy@fix_Science2}
{1540}{}{PID_POLE_DART_LOW@выстругиваем небольшие деревянные дротики.@SK_OUTDOORSMAN 40@SK_OUTDOORSMAN 40@PID_FIREWOOD 1@PID_KNIFE 1@PID_POLE_DART_LOW 2@}
{1545}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Заместите этой смесью газ в одном из баллонов сварки.@SK_SCIENCE 30@SK_SCIENCE 40&SK_REPAIR 50@PID_CHEMICALS 2&PID_CRAFT_M_JUNK 2&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1&PID_WELDING 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_FLAMETHROWER_FUEL 10@script fix_boy@fix_Advanced}
{1550}{}{PID_FLAMETHROWER_FUEL@Найдите в мусоре побольше пенопласта, растворяйте в ацетоне, пока эта смесь не станет густой. Дозаправьте баллон с топливом.@SK_SCIENCE 30@SK_SCIENCE 50&SK_REPAIR 80@PID_FLAMETHROWER_FUEL 1&PID_ROT_GUT 1&PID_CHEMICALS 1&PID_CRAFT_M_JUNK 1&PID_WORKBENCH_TOKEN 1@PID_CHEMISTRY_MANUAL 1@PID_FLAMETHROWER_FUEL 10@script fix_boy@fix_Advanced}
{1555}{}{PID_GRENADELAUNCHER_AMMO@За основу снаряда берем какую-нибудь металлическую банку. Сыпем на дно пороха, делаем отверстие и накрываем дно. Делаем шрапнелевые снаряды из железяк, запаиваем крышку. Заряд неплохого качества готов!@@SK_REPAIR 100&SK_SCIENCE 100&SK_BIG_GUNS 50@PID_CRAFT_M_BARS 4&PID_SHORT_TUBE 1&PID_GUNPOWDER 2&PID_BANKA_MEH 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_GRENADELAUNCHER_AMMO 1@script fix_boy@fix_Science}

// броня
{1800}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{1805}{}{PID_PURPLE_ROBE@Перекрасьте скучную песочную робу в удивительный цвет фиолетовой принцессы!@@SK_OUTDOORSMAN 40@PID_SANDROBE 1&PID_BROC_FLOWER 5&PID_BOOZE 1@@PID_PURPLE_ROBE 1@script fix_boy@fix_FreeHands}
{1810}{}{PID_SANDROBE@Сшейте из старых кусков ткани один большой мешок, а потом добавьте к нему капюшон и рукава.@@SK_OUTDOORSMAN 50@PID_CRAFT_L_RAGS 12&PID_CRAFT_L_LINT 4&PID_MEDTHREAD 4@PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_SANDROBE 1@script fix_boy@fix_FreeHands}
{1815}{}{PID_LEATHER_JACKET@Сшейте куртку из кусков шкур и ткани. По последней моде без одного рукава.@@SK_OUTDOORSMAN 70|SK_SCIENCE 40&SK_REPAIR 40@PID_CRAFT_L_HIDE 8&PID_CRAFT_L_LINT 2&PID_MEDTHREAD 4@PID_SHIV 1&PID_SCISSORS 1&PID_CUTTHROAT 1&PID_MEDNEEDLE 1@PID_LEATHER_JACKET 1@script fix_boy@fix_Advanced}
{1820}{}{PID_CURED_LEATHER_ARMOR@Что бы увеличить защиту от скользящих ударов и при этом не потерять мобильность, вы пришиваете небольшие куски вываренной кожи к открытым частям одежды. Добавьте кожаный пояс, пару карманов.@@SK_SCIENCE 80&SK_REPAIR 100&@PID_LEATHER_JACKET 1&PID_BOTTLE_FULL 4&PID_CRAFT_L_HIDE 4&PID_CRAFT_L_LINT 2&PID_CRAFT_L_RAGS 4&PID_MEDTHREAD 4@PID_SHIV 1&PID_SCISSORS 1&PID_MEDNEEDLE 1@PID_CURED_LEATHER_ARMOR 1@exp 100 script fix_boy@fix_Repair}
{1825}{}{PID_CURED_LEATHER_ARMOR_MK_II@Совершенно другой подход к решению проблемы защиты открывается при использовании небольших бронепластин. Переделав нашлёпки из кожи в карманы для пластин, вы добиваетесь разительного увеличения защиты от проникающих и касательных ударов, жертвуя мобильностью.@@SK_SCIENCE 130&SK_REPAIR 120@PID_CURED_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_PB_PLATE 6&PID_CRAFT_L_LINT 1&PID_MEDTHREAD 2@PID_WORKBENCH_TOKEN 1&PID_MEDNEEDLE 1&PID_SHIV 1&PID_SCISSORS 1@PID_CURED_LEATHER_ARMOR_MK_II 1@exp 200 script fix_boy@fix_Repair}
{1830}{}{PID_LEATHER_ARMOR@Вываренная дублёная кожа - отличный материал для обеспечения полной защиты вашего тела.@@SK_OUTDOORSMAN 150|SK_REPAIR 100&SK_SCIENCE 50@PID_BOTTLE_FULL 6&PID_CRAFT_L_HIDE 12&PID_CRAFT_L_LINT 4&PID_MEDTHREAD 6@PID_FIREPLACE_TOKEN 1&PID_MEDNEEDLE 1&PID_SHIV 1&PID_KNIFE 1|PID_SCISSORS 1|PID_CUTTHROAT 1@PID_LEATHER_ARMOR 1@exp 100 script fix_boy@fix_Repair}
{1835}{}{PID_LEATHER_ARMOR_MK_II@Берем за основу прочную шкуру золотого геккона, обрабатываем ее для усиления защитных свойств.@@SK_OUTDOORSMAN 50&SK_REPAIR 110&SK_SCIENCE 150@PID_LEATHER_ARMOR 1&PID_ROPE 1&PID_GOLDEN_GECKO_PELT 2&PID_CHEMICALS 1&PID_MEDTHREAD 4&PID_CRAFT_L_LINT 2@PID_WORKBENCH_TOKEN 1&PID_MEDNEEDLE 1&PID_SHIV 1&PID_SCISSORS 1@PID_LEATHER_ARMOR_MK_II 1@exp 250 script fix_boy@fix_Advanced}
{1840}{}{PID_METAL_ARMOR@Выпрямив несколько листов ржавого железа, вы использовали их для укрепления брони. Затем привариваем несколько шипов на наплечник, для пущей крутости. Громоздко, грубо, но сука, внушительно!@@SK_REPAIR 120&SK_SCIENCE 100@PID_LEATHER_ARMOR 1&PID_METAL_LIST_MEH 6&PID_CRAFT_M_BARS 4&PID_SPIKE_MEH 4@PID_SLEDGEHAMMER 1&PID_WORKBENCH_TOKEN 1&PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_METAL_ARMOR 1@exp 150 script fix_boy@fix_Repair}
{1845}{}{PID_METAL_ARMOR_MK_II@Меняем ржавые и грубые пластины на качественные металические листы. Делаем удобные подкладки для кожи, полируем всё.@@SK_REPAIR 160&SK_SCIENCE 180@PID_METAL_ARMOR 1&PID_IRON_PLATE 4&PID_CRAFT_M_BARS 5&PID_CHEMICALS 1&PID_CRAFT_L_HIDE 2&PID_MEDTHREAD 2&PID_CRAFT_L_LINT 1@PID_SLEDGEHAMMER 1&PID_WORKBENCH_TOKEN 1&PID_WELDING 1&PID_SUPER_TOOL_KIT 1@PID_METAL_ARMOR_MK_II 1@script fix_boy@fix_HighTech}
{1850}{}{PID_MANTIS_ARMOR@Присобачиваем внахлест кучу хитиновых пластин на кожаную броню. Панцирь болотника идет на нагрудник.@SK_OUTDOORSMAN 150&SK_REPAIR 50@SK_OUTDOORSMAN 80&SK_REPAIR 60@PID_LEATHER_ARMOR 1&PID_CRAFT_L_HIDE 2&PID_CRAFT_L_LINT 2&PID_MEDTHREAD 1&PID_MIRELUK_SHELL 1&PID_MANTIS_SHELL 12@PID_WORKBENCH_TOKEN 1&PID_SHIV 1&PID_MEDNEEDLE 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1@PID_MANTIS_ARMOUR 1@script fix_boy@fix_Repair}
{1855}{}{PID_MUMARMOR@Чтобы воссоздать эту внушительную конструкцию нужно быть настоящим гением механики. Учтите, на это уйдет кучу сварки.@SK_REPAIR 160@SK_SCIENCE 180&SK_REPAIR 200@PID_CRAFT_M_BARS 8&PID_CRAFT_L_HIDE 8&PID_MEDTHREAD 4&PID_CRAFT_L_LINT 4&PID_CRAFT_M_JUNK 2&PID_WELDING 1&PID_IRON_PLATE 8@PID_SUPER_TOOL_KIT 1@PID_MUMARMOR 1&PID_WELDING_USED 1@script fix_boy@fix_Advanced}
{1860}{}{PID_MUJACKET@Кожанная куртка для мутантов. Технология производста почти не отличается от обычной, но материала уходит в два раза больше.@@SK_REPAIR 80&SK_SCIENCE 80@PID_CRAFT_L_HIDE 16&PID_CRAFT_L_LINT 4&PID_MEDTHREAD 8&PID_CHEMICALS 2@PID_WORKBENCH_TOKEN 1&PID_SHIV 1&PID_SCISSORS 1&PID_KNIFE 1|PID_COMBAT_KNIFE 1&PID_CUTTHROAT 1@PID_MUJACKET 1@script fix_boy@fix_Advanced}

// очкострелы стандарт
{2000}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{2005}{}{PID_SPEARTHROWER1_LOW@"Пара пружин, рычаги и рама" - так вы думали, пока не поняли что без калибровки и доводки оно швыряет болты куда попало и постоянно делает осечки. Но это всё уже позади.@@SK_SMALL_GUNS 50&SK_SCIENCE 50&SK_REPAIR 50@PID_CRAFT_M_JUNK 2&PID_WOOD_PLANK 1&PID_DETAL_MEH 1&PID_HLAM_MEH 1|PID_HLAM2_MEH 1|PID_METAL_LIST_MEH 1&PID_CLUB 1&PID_ROPE 1|PID_CRAFT_M_BARS 2@PID_MULTI_TOOL 1@PID_SPEARTHROWER1 1@exp 100 script fix_boy@fix_FreeHands}
{2010}{}{PID_SPRINGER_RIFLE@Примитивный мушкет малого калибра из подручных средств. Ствол очень быстро забивается пороховыми газами.@@SK_SMALL_GUNS 50&SK_REPAIR 50@PID_TUBE 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 2&PID_FLINT 1&PID_WOOD_PLANK 1@@PID_SPRINGER_RIFLE 1@exp 50 script fix_boy@fix_FreeHands}
{2015}{}{PID_ZIP_GUN@Прочно примотайте трубу проволокой к рукояти. Отнеситесь к этому серьёзно, иначе ваше оружие самоуничтожится после первого же выстрела.@@SK_SMALL_GUNS 20&SK_REPAIR 40@PID_SHORT_TUBE 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1&PID_FLINT 1&PID_WOOD_PLANK 1@@PID_ZIP_GUN 1@exp 50 script fix_boy@fix_FreeHands}
{2020}{}{PID_REVOLVER_LOW@Самодельный револьвер. Барабан, курок и ствол, простецкая механика.@@SK_SMALL_GUNS 50&SK_REPAIR 70&SK_SCIENCE 50@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_REVOLVER_PART 1&PID_ELECTO_MEH 1&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_REVOLVER_LOW 1@exp 100 script fix_boy@fix_FreeHands}
{2025}{}{PID_PISTOL_LOW@Использовав черкаш за основу, вы собираете примитивный пистолет. Он явно нуждается в доработке.@@SK_SMALL_GUNS 60&SK_REPAIR 90&SK_SCIENCE 70@PID_ZIP_GUN 1&PID_SHORT_TUBE 1&PID_SOED_MEH 1&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_PISTOL_LOW 1@exp 50 script fix_boy@fix_Repair}
{2030}{}{PID_REV_RIFLE_LOW@Переделываем дерьмовый самопал под что-то более приятное.@@SK_SMALL_GUNS 70&SK_REPAIR 100&SK_SCIENCE 80@PID_SPRINGER_RIFLE 1&PID_REVOLVER_LOW 1&PID_ELECTO_MEH 1&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_REV_RIFLE_LOW 1@exp 150 script fix_boy@fix_FreeHands}
{2035}{}{PID_DRUM_GUN_LOW@После многих часов проведенных за деланием чертежа, вы придумали что-то эдакое.@@SK_SMALL_GUNS 100&SK_REPAIR 100&SK_SCIENCE 150@PID_WOOD_PLANK 2&PID_TUBE 1&PID_ELECTO_MEH 1&PID_DETAL_MEH 1&PID_PERED_MEH 1&PID_CRAFT_M_BARS 2&PID_IRON_DETALS 1&PID_CRAFT_M_JUNK 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1&PID_WELDING 1@PID_DRUM_GUN_LOW 1@exp 300 script fix_boy@fix_Repair}
{2040}{}{PID_SNIPER_GUN_LOW@Переточка под другой калибр и усиление ствола позволяют превратить жалкий мушкет в грозную винтовку.@@SK_SMALL_GUNS 100&SK_REPAIR 150&SK_SCIENCE 100@PID_SPRINGER_RIFLE 1&PID_TUBE 2&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 2&PID_SOED_MEH 1&PID_ELECTO_MEH 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SNIPER_GUN_LOW 1@script fix_boy@fix_Advanced}
{2045}{}{PID_LOW_SNIPER2@Заменяем громоздкие детали на облегченные, выпиливаем лишнее, улучшаем ствол и механику. Теперь с этим можно ходить!@@SK_SMALL_GUNS 150&SK_REPAIR 100&SK_SCIENCE 125@PID_SNIPER_GUN_LOW 1&PID_CRAFT_M_JUNK 2&PID_PERED_MEH 1&PID_CRAFT_M_BARS 2&PID_TUBE 1&PID_CRAFT_M_STEL 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_LOW_SNIPER2 1@exp 100 script fix_boy@fix_Advanced}
{2050}{}{PID_SMOKE_GUN_LOW@Настоящий король среди мусорных постядерных пушек! Переточите ствол под меньший калибр и модернизировав зарядно-спусковой механизм, вы вытачиваете из старой банки неснимаемый самодельный глушитель, позволяющий не выдавать себя при стрельбе.@@SK_SMALL_GUNS 85&SK_REPAIR 150&SK_SCIENCE 100@PID_PISTOL_LOW 1&PID_WOOD_PLANK 1&PID_TUBE 1&PID_DETAL_MEH 1&PID_BANKA_MEH 1&PID_CRAFT_L_RAGS 2&PID_CRAFT_M_JUNK 1&PID_CRAFT_M_BARS 2@PID_MULTI_TOOL 1&PID_WORKBENCH_TOKEN 1@PID_SMOKE_GUN_LOW 1@script fix_boy@fix_Advanced}
{2055}{}{PID_AUTOGUN_LOW@Берем хорошенький пистолет, модернизируем затворный механизм, для автовзвода, закрываем корпусом. Громоздко, но работает. Другой пистолет не подходит категорически, поэтому постарайтесь найти старенький кольт.@SK_SMALL_GUNS 30@SK_REPAIR 80&SK_SCIENCE 100@PID_CRAFT_M_JUNK 2&PID_TUBE 1&PID_CRAFT_M_BARS 1&PID_10MM_PISTOL 1&PID_DETAL_MEH 1&PID_METAL_LIST_MEH 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1&PID_WELDING 1@PID_AUTOGUN_LOW 1@script fix_boy@fix_Advanced}
{2060}{}{PID_SAWED_OFF_SHOTGUN@Укорачивание ствола на десяток дюймов позволит комфортно прятать дробовик под одеждой, чтобы удивлять противника в самый неподходящий момент.@SK_REPAIR 20@SK_REPAIR 30@PID_SHOTGUN 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SAWED_OFF_SHOTGUN 1@script fix_boy@fix_Repair}
{2065}{}{PID_SHOTGUN@Мощный короткоствольный дробовик. Мечта любого фермера. Обычно на боку вырезают какую-нибудь красивую гравировку...@@SK_REPAIR 165&SK_SMALL_GUNS 100&SK_SCIENCE 125@PID_WOOD_PLANK 2&PID_IRON_DETALS 2&PID_EMKOCT_MEH 1&PID_TUBE 2&PID_SOED_MEH 2&PID_DETAL_MEH 1&PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 4@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_SHOTGUN 1@script fix_boy@fix_Advanced}
{2070}{}{PID_SHOTPISTOL_LOW@Берем парочку труб подходящего диаместра, воруем спусковой механизм у простенького пистолета, модернизируем, тщательно закрепляем и получаем подобие обреза.@@SK_SMALL_GUNS 80&SK_REPAIR 150&SK_SCIENCE 100@PID_PISTOL_LOW 1&PID_SHORT_TUBE 2&PID_DETAL_MEH 1&PID_CRAFT_M_BARS 1&PID_CRAFT_M_JUNK 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_SHOTPISTOL_LOW 1@script fix_boy@fix_Advanced}
{2075}{}{PID_GECKO_LOW@Замечательный гладкоствольный дробовик для охоты на мелкую и среднюю дичь. Делается на основе мушкета.@@SK_REPAIR 100&SK_SMALL_GUNS 75&SK_SCIENCE 75@PID_SPRINGER_RIFLE 1&PID_TUBE 1&PID_WOOD_PLANK 2&PID_BANKA_MEH 1&PID_SOED_MEH 1&PID_DETAL_MEH 1&PID_ELECTO_MEH 1&PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 2@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_GECKO_LOW 1@script fix_boy@fix_Advanced}


// очкострелы для мамкиных выходцев из анклава
{2200}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{2205}{}{PID_LASER_PISTOL_LOW@Комбинация линз с кустарными конденсаторами, источником энергии и системой охлаждения может сделать его вполне реальным оружием.@@SK_ENERGY_WEAPONS 75&SK_REPAIR 100&SK_SCIENCE 125@PID_SPECTACLES 2&PID_CRAFT_E_LAMP 2&PID_EXCAVATOR_CHIP 2&PID_CRAFT_E_CHIP 1&PID_IRON_DETALS 2&PID_METAL_LIST_MEH 1&PID_SOED_MEH 2&PID_OHLAD_MEH 1&PID_ELECTO_MEH 1&PID_CRAFT_M_JUNK 2&PID_CRAFT_M_BARS 4@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_PISTOL_LOW 1@script fix_boy@fix_HighTech}
{2210}{}{PID_LASER_PISTOL_LOW2@Модернизируем систему охлаждения, устанавливаем дополнительные линзы для мощности, калибруем, и готово!@@SK_ENERGY_WEAPONS 80&SK_REPAIR 120&SK_SCIENCE 150@PID_LASER_PISTOL_LOW 1&PID_SPECTACLES 1&PID_CRAFT_E_LAMP 1&PID_EXCAVATOR_CHIP 2&PID_IRON_DETALS 1&PID_SOED_MEH 1&PID_OHLAD_MEH 1&PID_CRAFT_E_CHIP 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_PISTOL_LOW2 1@script fix_boy@fix_HighTech}
{2215}{}{PID_PLASMA_SMG_LOW@Излучатель, отражатели, камера для энергоячеек, вот вроде и все.@SK_ENERGY_WEAPONS 100@SK_REPAIR 120&SK_SCIENCE 140@PID_METAL_LIST_MEH 1&PID_IRON_DETALS 1&PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 3&PID_TUBE 2&PID_ELECTO_MEH 1&PID_EXCAVATOR_CHIP 1&PID_CRAFT_E_LAMP 2&PID_CRAFT_E_CHIP 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_PLASMA_SMG_LOW 1@script fix_boy@fix_Advanced}
{2220}{}{PID_LASER_RIFLE_LOW@Собираем корпус, вставляем линзы для усиления луча от батарейки, устанавливаем электронику, настраиваем систему охлаждения, и вуаля! Можем идти пугать дикарей нано-технологиями.@@SK_ENERGY_WEAPONS 100&SK_REPAIR 150&SK_SCIENCE 200@PID_LASER_PISTOL_LOW 1|PID_LASER_PISTOL_LOW2 1&PID_IRON_PLATE 1&PID_IRON_DETALS 2&PID_SOED_MEH 1&PID_OHLAD_MEH 1&PID_CRAFT_E_LAMP 2&PID_CRAFT_E_CHIP 1&PID_EXCAVATOR_CHIP 2&PID_SPECTACLES 2@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_LASER_RIFLE_LOW 1@exp 500 script fix_boy@fix_HighTech}

// очкострелы для сильных мушчин
{2300}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{2305}{}{PID_SPEARTHROWER2@Тот же копьемет, только с помпой и двумя ствольными каналами.@@SK_BIG_GUNS 75&SK_SCIENCE 75&SK_REPAIR 100@PID_TUBE 2&PID_DVIGAT_MEH 1&PID_EMKOCT_MEH 2&PID_CRAFT_M_JUNK 4&PID_DETAL_MEH 1&PID_CLUB 1&PID_ROPE 1|PID_CRAFT_M_BARS 3@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_SPEARTHROWER2 1@script fix_boy@fix_Advanced}
{2310}{}{PID_BIGGUN_LOW@Берём трубу большую. Скрепляем всё различными заклёпками и стяжками, делаем примитивный спусковой механизм. Для удобства делаем деревянный приклад-рукоять. Бо-оже, ну и убожество мысли...@@SK_BIG_GUNS 50&SK_REPAIR 100&SK_SCIENCE 100@PID_TUBE 1&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 2&PID_DETAL_MEH 1&PID_WOOD_PLANK 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_BIGGUN_LOW 1@script fix_boy@fix_Advanced}
{2315}{}{PID_FLAMER@Одним сварочным аппаратом совершаем магическое превращение груды металла в тело огнемёта, а вторым привариваем горелку и систему подачи топлива первого к этой конструкции.@SK_REPAIR 90@SK_REPAIR 125&SK_SCIENCE 150&SK_BIG_GUNS 125@PID_EMKOCT_MEH 1&PID_TUBE 3&PID_IRON_DETALS 4&PID_CRAFT_M_BARS 4&PID_CRAFT_M_JUNK 5&PID_DETAL_MEH 1&PID_LIGHTER 1&PID_FLAMETHROWER_FUEL 1@PID_SUPER_TOOL_KIT 1&PID_WELDING 1&PID_WORKBENCH_TOKEN 1@PID_FLAMER 1@script fix_boy@fix_HighTech}
{2320}{}{PID_SAWGUN_LOW@Собираем раму, устанавливаем движок, натягиваем цепь и передаточный механизм для катапульты.@SK_BIG_GUNS 100@SK_REPAIR 150&SK_SCIENCE 150&SK_BIG_GUNS 40@PID_IRON_PLATE 1&PID_DVIGAT_MEH 2&PID_CRAFT_M_BARS 6&PID_CRAFT_M_JUNK 4&PID_TUBE 2&PID_MOTOR 1&PID_CHAIN 2&PID_PERED_MEH 1&PID_WORKBENCH_TOKEN 1@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_SAWGUN_LOW 1@script fix_boy@fix_Advanced}
{2325}{}{PID_ONEHAND_ROCKET_LAUNCHER@Самодельный гранатомет.. Крайне опасен как для противника, так и для обладателя. Серьезно.@@SK_BIG_GUNS 100&SK_REPAIR 110&SK_SCIENCE 125@PID_TUBE 1&PID_IRON_DETALS 1&PID_SOED_MEH 2&PID_CRAFT_M_JUNK 3&PID_CRAFT_M_BARS 2&PID_ELECTO_MEH 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1&PID_WELDING 1@PID_ONEHAND_ROCKET_LAUNCHER 1@exp 200 script fix_boy@fix_Advanced}
{2330}{}{PID_GATLING_LOW@Ваших знаний тяжелого оружия и истории достаточно чтобы смастерить простейший Гатлинг.@@SK_BIG_GUNS 75&SK_REPAIR 120&SK_SCIENCE 110@PID_TUBE 6&PID_REVOLVER_PART 1&PID_ELECTO_MEH 1&PID_PERED_MEH 1&PID_DETAL_MEH 1&PID_CRAFT_M_STEL 1&PID_CRAFT_M_BARS 3&PID_CRAFT_M_JUNK 3&@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1&PID_WELDING 1@PID_GATLING_LOW 1@exp 100 script fix_boy@fix_FreeHands}
{2335}{}{PID_QUADRO_SHOTGUN@Для стволов берем за основу трубы, затем, придется реально повозится с механикой, но оно того стоит!@@SK_BIG_GUNS 65&SK_REPAIR 110&SK_SCIENCE 75@PID_TUBE 4&PID_CRAFT_M_BARS 2&PID_CRAFT_M_JUNK 3&PID_DETAL_MEH 1&PID_ELECTO_MEH 1&PID_DVIGAT_MEH 1&PID_WOOD_PLANK 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WORKBENCH_TOKEN 1@PID_QUADRO_SHOTGUN 1@exp 200 script fix_boy@fix_Advanced}
{2340}{}{PID_14mm_BIGGUN2_LOW@Обычная винтовка, но для ребят с мышцами покрупнее. Не забудьте сделать дырки в стволе для охлаждения! Перегревается этот агрегат будь здоров.@@SK_BIG_GUNS 90&SK_SCIENCE 90&SK_REPAIR 125@PID_TUBE 2&PID_METAL_LIST_MEH 3&PID_SOED_MEH 1&PID_ELECTO_MEH 1&PID_CRAFT_M_JUNK 3&PID_DETAL_MEH 1&PID_CRAFT_M_BARS 3@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_14mm_BIGGUN2_LOW 1@exp 100 script fix_boy@fix_Advanced}

// ловушки, взрывчатка. Сделайте кто-нибудь иконки, пжлста
{2400}{}{DEVIDER@Просто разделитель типов крафта.@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
{2410}{}{PID_DYNAMITE@Смешайте нитроглицерин с порошком для получения клейкой массы. Перемешайте её с опилками, скатайте в цилиндры и дайте высохнуть. Присоедините взрыватель.@@SK_OUTDOORSMAN 30&SK_SCIENCE 80&SK_TRAPS 100&SK_REPAIR 100@PID_NITROGLYCERIN 3&PID_HEALING_POWDER 2&PID_FIREWOOD 1&PID_CRAFT_E_CHIP 1&PID_PART_OF_ROPE 3@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_CHEMISTRY_MANUAL 1@PID_DYNAMITE 1@exp 200 script fix_boy@fix_HighTech}
{2415}{}{PID_PLASTIC_EXPLOSIVES_DULL@Найдите в мусоре какой-нибудь пластик, нагрейте его до плавления и вмешивайте в него порошок гексогена. Всё, теперь он удобен для хранения.@@SK_TRAPS 125&SK_SCIENCE 130@PID_CRAFT_M_JUNK 1|PID_BOTTLE_EMPTY 2&PID_HEXOGEN 1&PID_WORKBENCH_TOKEN 1@PID_LIGHTER 1@PID_PLASTIC_EXPLOSIVES_DULL 1@script fix_boy@fix_Advanced}
{2420}{}{PID_PLASTIC_EXPLOSIVES@Соберите радиодетонатор перепаяв микросхему и пару деталей.@@SK_REPAIR 130&SK_TRAPS 120@PID_CRAFT_M_JUNK 2&PID_PLASTIC_EXPLOSIVES_DULL 2&PID_CRAFT_E_LAMP 1&PID_CRAFT_E_CHIP 1&PID_WORKBENCH_TOKEN 1@PID_CHEMISTRY_MANUAL 1|PID_SUPER_TOOL_KIT 1@PID_PLASTIC_EXPLOSIVES 1@script fix_boy@fix_HighTech}
{2425}{}{PID_MINE@Высыпьте гексоген в качественную заготовку для мины, соорудите простенький взрыватель с использованием капсюля ружейного патрона.@@SK_TRAPS 130&SK_SCIENCE 100&SK_REPAIR 100&SK_OUTDOORSMAN 80@PID_HEXOGEN 1&PID_IRON_DETALS 1&PID_SHOTGUN_SHELLS 1&PID_WORKBENCH_TOKEN 1@PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_MINE 1@script fix_boy@fix_HighTech}
{2430}{}{PID_TRAP_ELECTRIC@Электрическая ловушка. Как это ни странно, но она бьет током.@@SK_TRAPS 75&SK_SCIENCE 150&SK_REPAIR 100@PID_OHLAD_MEH 1&PID_CRAFT_E_CHIP 1&PID_CRAFT_M_BARS 3&PID_SMALL_ENERGY_CELL 5@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1@PID_TRAP_ELECTRIC 1@script fix_boy@fix_Repair}
{2435}{}{PID_TRAP_FIRE_BREATH@Дыхание гекко. Делаем простое подобие огнемета из подручных средств, делаем датчик движения и присоединяем к активатору.@@SK_REPAIR 100&SK_SCIENCE 150@PID_DETAL_MEH 1&PID_CRAFT_M_JUNK 2&PID_LIGHTER 1&PID_CRAFT_M_BARS 3&PID_FLAMETHROWER_FUEL 5@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_TRAP_FIRE_BREATH 1@script fix_boy@fix_Repair}
{2440}{}{PID_TRAP_KNIFES@Делаем пружину и соединяем проволкой с чем-либо в контейнере. Ловушка ножи, просто засуньте в ящик или дверь, и пальцам незатейливого домушника не поздоровится.@@SK_REPAIR 100&SK_SCIENCE 75&SK_TRAPS 50@PID_KNIFE 5&PID_PART_OF_ROPE 3&PID_CRAFT_M_BARS 2@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_TRAP_KNIFES 1@script fix_boy@fix_Repair}
{2445}{}{PID_TRAP_CANISTER_SHOT@Можно сделать так, чтобы противнику прилетело в лицо сотню мелких металлических шариков. Стоит лишь ему позарится на ваши вещи...@@SK_REPAIR 150&SK_SCIENCE 125&SK_TRAPS 100@PID_BBS 100&PID_GUNPOWDER 1&PID_TUBE 1&PID_CRAFT_M_JUNK 3&PID_ROPE 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_TRAP_CANISTER_SHOT 1@script fix_boy@fix_Repair}
{2450}{}{PID_TRAP_STUNNER@Электрошокер, еще одно отличное средство вырубить незваных гостей. Пятизарядный.@@SK_TRAPS 125&SK_SCIENCE 175&SK_REPAIR 100@PID_OHLAD_MEH 1&PID_ELECTO_MEH 1&PID_CRAFT_E_CHIP 1&PID_CRAFT_M_BARS 4&PID_SMALL_ENERGY_CELL 10@PID_WORKBENCH_TOKEN 1&PID_SUPER_TOOL_KIT 1&PID_WELDING 1@PID_TRAP_STUNNER 1@exp 150 script fix_boy@fix_Repair}
{2455}{}{PID_TRAP_SLEDGE_HAMMER@Кувалда на двери - отличный спобок вырубить воришку.@@SK_REPAIR 50&SK_TRAPS 50&SK_SCIENCE 75@PID_SLEDGEHAMMER 1&PID_ROPE 1@PID_SHIV 1|PID_KNIFE 1|PID_THROWING_KNIFE 1@PID_TRAP_SLEDGE_HAMMER 1@script fix_boy@fix_Repair}
{2460}{}{PID_TRAP_POISON_BLADE@Отравленые ножи - приятный сюрприз для нежданых гостей.@@SK_OUTDOORSMAN 60@PID_TRAP_KNIFES 1&PID_RADSCORPION_PARTS 6@PID_BANKA_MEH 1@PID_TRAP_POISON_BLADE 1@script fix_boy@fix_Repair}
{2465}{}{PID_TRAP_ITEM_BREAKER@Ловушка, уничтожающая все вещи в ящике. Будьте осторожней.@@SK_TRAPS 160&SK_SCIENCE 150&SK_REPAIR 100@PID_CRAFT_M_BARS 5&PID_IRON_PLATE 1&PID_DETAL_MEH 1@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_TRAP_ITEM_BREAKER 1@exp 100 script fix_boy@fix_Repair}
{2470}{}{PID_TRAP_STAKE@Не пораньте глаза при установке этих кольев.@@SK_TRAPS 100&SK_OUTDOORSMAN 100@PID_SHARPENED_POLE 4&PID_CRAFT_M_BARS 2&PID_PART_OF_ROPE 4@PID_WORKBENCH_TOKEN 1&PID_MULTI_TOOL 1|PID_SUPER_TOOL_KIT 1@PID_TRAP_STAKE 1@script fix_boy@fix_Repair}
{1488228}{}{END@Пустышка@@@PID_DEVIDER 1@@PID_DEVIDER 1@}
